### ISSUE TITLE
how do you build wine-staging in yml file , can you tell me step and command

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/wine_appimage#2]

**Comment by lucasmz1** [comment]
Here I use the GitHub actions. First you need to setup an workflow and also enable the read write option on your repository.
Second is setup the Shell script which will donwload for an Ubuntu live iso the necessary contents to build the appimage. Everything you can find in my main repository where is located on in this wine appimage repository. But you can skip all this step and download the version from taqi raza he provides wine staging and stable versions. Search on Google for mmnrt wine appimge. But if you are really interested to provide that join my group on telegram called appimage users. There we can discuss more about this wine appimage I can give you more information about it to you over there.

**Comment by lucasmz1** [comment]
Well the second tip I can give you is to clone my repository and copy and paste from the wine repository the name of the .Deb file which has the name of the binary named staging. It's not difficult. I can do that if you really want the staging version.

**Comment by lucasmz1** [comment]
But if you want to build it offline I can teach you. All you may need is the yml file with the recipe and also the appimage-builder. Provided by appimge crafters on GitHub. This is a shortcut to all I have spoken above.
