### ISSUE TITLE
please merge mono

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/wine_appimage#5]
![image](https://github.com/lucasmz1/wine_appimage/assets/87791643/ab3cdbb8-ee09-4709-a5a9-9f882ac1e5a8)

**Comment by lucasmz1** [comment]
@newyorkthink 

well mono is packeck along side on wine you can see that, if you give an ./wine_appImage --appimage-extract, it's linked through the comand ln -rs which generate in a folder ~/.cache/wine/ but to be honest it never worked for me.

I'll be honest I copied and modified this code from taqi raza well known as mmnrt on github, you can also use his wine he did a great advance towards wine.
I'll try to improve this on a near future.
but thnaks for the bug report I promise try to do something in the future about that.
