### ISSUE TITLE
hi cannot run

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/wine_appimage#7]
![image](https://github.com/lucasmz1/wine_appimage/assets/87791643/4f885f41-51f3-43cf-9e9d-4f4181a85780)
![image](https://github.com/lucasmz1/wine_appimage/assets/87791643/24cab1d7-1bcf-429d-ba0a-de2781926ce2)

**Comment by lucasmz1** [comment]
Hi, I have added WINESERVER env variable to the project, download the new build and try again.
thank you for reporting this bug. keep reporting as fast as you can.
wants again tanks for helping me.

**Comment by lucasmz1** [comment]
I see other detail, you are running on an VM, have you tried outside the VM ? this could be the root of the problem.

**Comment by lucasmz1** [comment]
Try to run outside the VM, maybe the vm doesn't allowed you to access the full system feature.
