### ISSUE TITLE
/tmp/.mount_wine-xsfA8nn/wrapper: line 80: /tmp/.mount_wine-xsfA8nn/usr/bin/wine: No such file or directory

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/wine_appimage#8]
cannot run it for host os
![image](https://github.com/lucasmz1/wine_appimage/assets/87791643/ab32f148-1eaf-457b-ac3a-bf346516f5ad)

**Comment by lucasmz1** [comment]
hello, try install glibc-i386, due to ubuntus lack of some gconv files it may not  work properly.
